import { Profile, Company, Store, Category, Product, StoreInventory } from './types';

export const INITIAL_PROFILES: Profile[] = [
    {
        id: 'usr-customer-1',
        auth_user_id: 'auth-cust-1',
        full_name: 'Dharshan Customer',
        email: 'customer@salestorm.demo',
        phone: '+91 98765 43210',
        role: 'CUSTOMER',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'usr-business-1',
        auth_user_id: 'auth-biz-1',
        full_name: 'TechZone Business Owner',
        email: 'business@salestorm.demo',
        phone: '+91 98765 43211',
        role: 'BUSINESS',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'usr-admin-1',
        auth_user_id: 'auth-admin-1',
        full_name: 'Platform Administrator',
        email: 'admin@salestorm.demo',
        phone: '+91 98765 43212',
        role: 'ADMIN',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
];

export const INITIAL_COMPANIES: Company[] = [
    {
        id: 'comp-techzone',
        name: 'TechZone Electronics Ltd',
        email: 'contact@techzone.com',
        phone: '+91 44 2800 1100',
        description: 'Premier electronics retail chain with express store pickup and same-day delivery.',
        logo_url: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=150&auto=format&fit=crop&q=80',
        owner_id: 'usr-business-1',
        status: 'ACTIVE',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'comp-digitalworld',
        name: 'Digital World Superstores',
        email: 'support@digitalworld.com',
        phone: '+91 422 2500 2200',
        description: 'Authorized retailer for top global consumer tech and smart home electronics.',
        logo_url: 'https://images.unsplash.com/photo-1526738549149-8e07eca6c147?w=150&auto=format&fit=crop&q=80',
        owner_id: 'usr-business-1',
        status: 'ACTIVE',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'comp-electromart',
        name: 'ElectroMart Digital Store',
        email: 'info@electromart.com',
        phone: '+91 452 2600 3300',
        description: 'Direct-from-manufacturer flagship stores with guaranteed low prices and warranty.',
        logo_url: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=150&auto=format&fit=crop&q=80',
        owner_id: 'usr-business-1',
        status: 'ACTIVE',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
];

export const INITIAL_STORES: Store[] = [
    {
        id: 'store-tz-tirunelveli',
        company_id: 'comp-techzone',
        name: 'TechZone Tirunelveli Flagship',
        address: '42 South Bypass Road, Near Bus Stand',
        city: 'Tirunelveli',
        state: 'Tamil Nadu',
        pincode: '627005',
        latitude: 8.7139,
        longitude: 77.7567,
        phone: '+91 462 250100',
        opening_time: '09:30 AM',
        closing_time: '09:30 PM',
        status: 'OPEN',
        company_name: 'TechZone Electronics Ltd',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'store-tz-madurai',
        company_id: 'comp-techzone',
        name: 'TechZone Madurai Central',
        address: '15 West Veli Street, Town Hall Rd',
        city: 'Madurai',
        state: 'Tamil Nadu',
        pincode: '625001',
        latitude: 9.9252,
        longitude: 78.1198,
        phone: '+91 452 250200',
        opening_time: '09:00 AM',
        closing_time: '09:00 PM',
        status: 'OPEN',
        company_name: 'TechZone Electronics Ltd',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'store-tz-chennai',
        company_id: 'comp-techzone',
        name: 'TechZone Chennai Mount Road',
        address: '108 Anna Salai, Thousand Lights',
        city: 'Chennai',
        state: 'Tamil Nadu',
        pincode: '600002',
        latitude: 13.0827,
        longitude: 80.2707,
        phone: '+91 44 2800100',
        opening_time: '10:00 AM',
        closing_time: '10:00 PM',
        status: 'OPEN',
        company_name: 'TechZone Electronics Ltd',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'store-tz-coimbatore',
        company_id: 'comp-techzone',
        name: 'TechZone Coimbatore RS Puram',
        address: '88 DB Road, RS Puram',
        city: 'Coimbatore',
        state: 'Tamil Nadu',
        pincode: '641002',
        latitude: 11.0168,
        longitude: 76.9558,
        phone: '+91 422 250300',
        opening_time: '09:30 AM',
        closing_time: '09:00 PM',
        status: 'OPEN',
        company_name: 'TechZone Electronics Ltd',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'store-dw-tirunelveli',
        company_id: 'comp-digitalworld',
        name: 'Digital World Palayamkottai',
        address: '12 Trivandrum High Rd, Palayamkottai',
        city: 'Tirunelveli',
        state: 'Tamil Nadu',
        pincode: '627002',
        latitude: 8.7289,
        longitude: 77.7081,
        phone: '+91 462 255400',
        opening_time: '09:00 AM',
        closing_time: '09:00 PM',
        status: 'OPEN',
        company_name: 'Digital World Superstores',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'store-dw-coimbatore',
        company_id: 'comp-digitalworld',
        name: 'Digital World Gandhipuram',
        address: '304 Cross Cut Road, Gandhipuram',
        city: 'Coimbatore',
        state: 'Tamil Nadu',
        pincode: '641012',
        latitude: 11.0045,
        longitude: 76.9612,
        phone: '+91 422 255500',
        opening_time: '09:30 AM',
        closing_time: '09:30 PM',
        status: 'OPEN',
        company_name: 'Digital World Superstores',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'store-em-chennai',
        company_id: 'comp-electromart',
        name: 'ElectroMart T. Nagar Mega Hub',
        address: '54 Usman Road, T. Nagar',
        city: 'Chennai',
        state: 'Tamil Nadu',
        pincode: '600017',
        latitude: 13.0604,
        longitude: 80.2496,
        phone: '+91 44 281155',
        opening_time: '10:00 AM',
        closing_time: '10:00 PM',
        status: 'OPEN',
        company_name: 'ElectroMart Digital Store',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'store-em-madurai',
        company_id: 'comp-electromart',
        name: 'ElectroMart KK Nagar Store',
        address: '80 KK Nagar Main Rd',
        city: 'Madurai',
        state: 'Tamil Nadu',
        pincode: '625020',
        latitude: 9.9312,
        longitude: 78.125,
        phone: '+91 452 281166',
        opening_time: '09:30 AM',
        closing_time: '09:00 PM',
        status: 'OPEN',
        company_name: 'ElectroMart Digital Store',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
];

export const INITIAL_CATEGORIES: Category[] = [
    { id: 'cat-smartphones', name: 'Smartphones', description: 'Latest 5G flagship smartphones, foldables, and accessories.', created_at: new Date().toISOString() },
    { id: 'cat-laptops', name: 'Laptops', description: 'High-performance ultrabooks, gaming laptops, and workstations.', created_at: new Date().toISOString() },
    { id: 'cat-tvs', name: 'TVs & Displays', description: '4K OLED, QLED Smart TVs, home audio, and projectors.', created_at: new Date().toISOString() },
    { id: 'cat-headphones', name: 'Headphones', description: 'Noise canceling wireless headphones, earbuds, and audiophile gear.', created_at: new Date().toISOString() },
    { id: 'cat-cameras', name: 'Cameras', description: 'Mirrorless cameras, lenses, vlogging gear, and drones.', created_at: new Date().toISOString() },
    { id: 'cat-gaming', name: 'Gaming Consoles', description: 'Next-gen consoles, VR headsets, controllers, and handhelds.', created_at: new Date().toISOString() },
    { id: 'cat-smartwatches', name: 'Smartwatches', description: 'Fitness trackers, outdoor GPS watches, and health bands.', created_at: new Date().toISOString() },
    { id: 'cat-accessories', name: 'Accessories', description: 'Keyboards, mice, docks, fast chargers, and storage drives.', created_at: new Date().toISOString() },
];

export const INITIAL_PRODUCTS: Product[] = [
    {
        id: 'prod-iphone17',
        category_id: 'cat-smartphones',
        brand: 'Apple',
        model: 'iPhone 17 Pro',
        name: 'Apple iPhone 17 Pro 256GB Titanium',
        description: 'A19 Pro chip, ProMotion 120Hz display, 48MP triple camera setup, action button, and all-day battery life.',
        sku: 'AAPL-IPH17P-256',
        price: 79999,
        images: ['https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&auto=format&fit=crop&q=80'],
        specifications: { Display: '6.3" Super Retina XDR OLED', Processor: 'A19 Pro Chip', Storage: '256GB', Camera: '48MP Main + 48MP Ultra Wide + 48MP Telephoto' },
        warranty: '1 Year Apple Official Warranty',
        status: 'ACTIVE',
        category_name: 'Smartphones',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'prod-samsung-s26',
        category_id: 'cat-smartphones',
        brand: 'Samsung',
        model: 'Galaxy S26 Ultra',
        name: 'Samsung Galaxy S26 Ultra 5G (512GB)',
        description: 'Snapdragon 8 Gen 5, integrated S Pen, 200MP Quad Camera system, and titanium frame.',
        sku: 'SMSNG-S26U-512',
        price: 74999,
        images: ['https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&auto=format&fit=crop&q=80'],
        specifications: { Display: '6.8" Dynamic AMOLED 2X 120Hz', Processor: 'Snapdragon 8 Gen 5', Storage: '512GB', RAM: '12GB' },
        warranty: '1 Year Samsung India Warranty',
        status: 'ACTIVE',
        category_name: 'Smartphones',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'prod-macbook-m3',
        category_id: 'cat-laptops',
        brand: 'Apple',
        model: 'MacBook Air 15" M3',
        name: 'Apple MacBook Air 15" M3 (16GB, 512GB)',
        description: 'Impossibly thin 15-inch Liquid Retina display, M3 8-Core CPU, 10-Core GPU, up to 18 hours battery life.',
        sku: 'AAPL-MBA15M3-512',
        price: 114900,
        images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop&q=80'],
        specifications: { Display: '15.3" Liquid Retina', Processor: 'Apple M3 8-Core', Memory: '16GB Unified', Storage: '512GB SSD' },
        warranty: '1 Year AppleCare',
        status: 'ACTIVE',
        category_name: 'Laptops',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'prod-dell-xps15',
        category_id: 'cat-laptops',
        brand: 'Dell',
        model: 'XPS 15 OLED',
        name: 'Dell XPS 15 Intel Core i9 (32GB, 1TB SSD)',
        description: '3.5K OLED InfinityEdge touch screen, NVIDIA GeForce RTX 4070, CNC aluminum body.',
        sku: 'DELL-XPS15-i9-1T',
        price: 145000,
        images: ['https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=600&auto=format&fit=crop&q=80'],
        specifications: { Display: '15.6" 3.5K OLED Touch', Processor: 'Intel Core i9-13900H', Graphics: 'RTX 4070 8GB', Storage: '1TB NVMe' },
        warranty: '2 Years Premium Support',
        status: 'ACTIVE',
        category_name: 'Laptops',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'prod-sony-wh1000xm6',
        category_id: 'cat-headphones',
        brand: 'Sony',
        model: 'WH-1000XM6',
        name: 'Sony WH-1000XM6 Wireless Noise Canceling Headphones',
        description: 'Industry-leading HD Noise Canceling Processor QN2, 40hr battery life, spatial audio, multipoint connection.',
        sku: 'SONY-WH1000XM6-BLK',
        price: 29990,
        images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80'],
        specifications: { NoiseCanceling: 'Active Dual-Processor', Battery: '40 Hours', Codecs: 'LDAC, AAC, SBC', Weight: '250g' },
        warranty: '1 Year Sony Official Warranty',
        status: 'ACTIVE',
        category_name: 'Headphones',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'prod-ps5-pro',
        category_id: 'cat-gaming',
        brand: 'Sony',
        model: 'PlayStation 5 Pro',
        name: 'Sony PlayStation 5 Pro Console (2TB SSD)',
        description: 'Advanced Ray Tracing, PlayStation Spectral Super Resolution (PSSR), 4K 120Hz gaming with DualSense wireless controller.',
        sku: 'SONY-PS5PRO-2TB',
        price: 54990,
        images: ['https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=600&auto=format&fit=crop&q=80'],
        specifications: { Storage: '2TB Custom High-Speed NVMe', GPU: '67% More CUs PSSR Engine', Video: '8K / 4K 120Hz HDR', Audio: 'Tempest 3D AudioTech' },
        warranty: '1 Year Sony India Warranty',
        status: 'ACTIVE',
        category_name: 'Gaming Consoles',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'prod-canon-r6m2',
        category_id: 'cat-cameras',
        brand: 'Canon',
        model: 'EOS R6 Mark II',
        name: 'Canon EOS R6 Mark II Mirrorless Camera (Body)',
        description: '24.2MP Full-Frame CMOS Sensor, 40 fps burst shooting, 4K60p 10-bit internal video, Dual Pixel CMOS AF II.',
        sku: 'CANON-EOSR6M2-BDY',
        price: 215000,
        images: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&auto=format&fit=crop&q=80'],
        specifications: { Sensor: '24.2MP Full-Frame', ContinuousBurst: 'Up to 40 fps', Video: 'Uncropped 4K 60p', Stabilization: 'In-Body 8.0 Stops IBIS' },
        warranty: '2 Years Canon India Warranty',
        status: 'ACTIVE',
        category_name: 'Cameras',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'prod-apple-watch-ultra2',
        category_id: 'cat-smartwatches',
        brand: 'Apple',
        model: 'Watch Ultra 2',
        name: 'Apple Watch Ultra 2 GPS + Cellular 49mm Titanium',
        description: 'Rugged 49mm titanium case, 3000 nits display, precision dual-frequency GPS, up to 72 hours low-power mode.',
        sku: 'AAPL-AWULT2-49',
        price: 89900,
        images: ['https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=600&auto=format&fit=crop&q=80'],
        specifications: { Case: '49mm Grade 5 Titanium', Display: '3000 Nits Always-On Retina', WaterResistance: '100m / EN13319 Dive Certified', Battery: 'Up to 72 Hrs' },
        warranty: '1 Year Apple Warranty',
        status: 'ACTIVE',
        category_name: 'Smartwatches',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'prod-samsung-tv-65',
        category_id: 'cat-tvs',
        brand: 'Samsung',
        model: 'Neo QLED 65" 4K',
        name: 'Samsung 65" Neo QLED 4K Smart TV (QN90C)',
        description: 'Quantum Matrix Tech with Mini LEDs, Neural Quantum Processor 4K, Dolby Atmos, 120Hz VRR gaming rate.',
        sku: 'SMSNG-TV65-QN90C',
        price: 129990,
        images: ['https://images.unsplash.com/photo-1593784991095-a205069470b6?w=600&auto=format&fit=crop&q=80'],
        specifications: { ScreenSize: '65 Inch', Resolution: '4K Ultra HD (3840 x 2160)', RefreshRate: '120Hz VRR', Audio: '60W 4.2.2 Channel Dolby Atmos' },
        warranty: '3 Years Comprehensive Warranty',
        status: 'ACTIVE',
        category_name: 'TVs & Displays',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 'prod-logitech-mxmaster3s',
        category_id: 'cat-accessories',
        brand: 'Logitech',
        model: 'MX Master 3S',
        name: 'Logitech MX Master 3S Performance Wireless Mouse',
        description: '8K DPI tracking on glass, quiet click tech, MagSpeed electromagnetic scrolling, USB-C fast charging.',
        sku: 'LOGI-MXM3S-GRAPHITE',
        price: 8995,
        images: ['https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format&fit=crop&q=80'],
        specifications: { Sensor: 'Darkfield High Precision 8000 DPI', Scroll: 'MagSpeed 1000 lines/sec', Connectivity: 'Bluetooth + Logi Bolt', Battery: '70 Days' },
        warranty: '1 Year Logitech Warranty',
        status: 'ACTIVE',
        category_name: 'Accessories',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
];

export const INITIAL_INVENTORY: StoreInventory[] = [
    // TechZone Tirunelveli
    { id: 'inv-tz-tvl-iphone17', store_id: 'store-tz-tirunelveli', product_id: 'prod-iphone17', available_quantity: 4, reserved_quantity: 0, sold_quantity: 12, version: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'inv-tz-tvl-ps5', store_id: 'store-tz-tirunelveli', product_id: 'prod-ps5-pro', available_quantity: 4, reserved_quantity: 0, sold_quantity: 16, version: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'inv-tz-tvl-macbook', store_id: 'store-tz-tirunelveli', product_id: 'prod-macbook-m3', available_quantity: 8, reserved_quantity: 0, sold_quantity: 5, version: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'inv-tz-tvl-sony-head', store_id: 'store-tz-tirunelveli', product_id: 'prod-sony-wh1000xm6', available_quantity: 15, reserved_quantity: 0, sold_quantity: 30, version: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },

    // TechZone Madurai
    { id: 'inv-tz-mdu-iphone17', store_id: 'store-tz-madurai', product_id: 'prod-iphone17', available_quantity: 8, reserved_quantity: 0, sold_quantity: 14, version: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'inv-tz-mdu-samsung', store_id: 'store-tz-madurai', product_id: 'prod-samsung-s26', available_quantity: 6, reserved_quantity: 0, sold_quantity: 9, version: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'inv-tz-mdu-ps5', store_id: 'store-tz-madurai', product_id: 'prod-ps5-pro', available_quantity: 10, reserved_quantity: 0, sold_quantity: 8, version: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },

    // TechZone Chennai
    { id: 'inv-tz-maa-iphone17', store_id: 'store-tz-chennai', product_id: 'prod-iphone17', available_quantity: 20, reserved_quantity: 0, sold_quantity: 45, version: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'inv-tz-maa-dell', store_id: 'store-tz-chennai', product_id: 'prod-dell-xps15', available_quantity: 5, reserved_quantity: 0, sold_quantity: 7, version: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'inv-tz-maa-canon', store_id: 'store-tz-chennai', product_id: 'prod-canon-r6m2', available_quantity: 3, reserved_quantity: 0, sold_quantity: 2, version: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },

    // Digital World Tirunelveli
    { id: 'inv-dw-tvl-iphone17', store_id: 'store-dw-tirunelveli', product_id: 'prod-iphone17', available_quantity: 12, reserved_quantity: 0, sold_quantity: 8, version: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'inv-dw-tvl-samsung', store_id: 'store-dw-tirunelveli', product_id: 'prod-samsung-s26', available_quantity: 15, reserved_quantity: 0, sold_quantity: 20, version: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'inv-dw-tvl-watch', store_id: 'store-dw-tirunelveli', product_id: 'prod-apple-watch-ultra2', available_quantity: 7, reserved_quantity: 0, sold_quantity: 11, version: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },

    // ElectroMart Chennai
    { id: 'inv-em-maa-iphone17', store_id: 'store-em-chennai', product_id: 'prod-iphone17', available_quantity: 20, reserved_quantity: 0, sold_quantity: 60, version: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'inv-em-maa-tv', store_id: 'store-em-chennai', product_id: 'prod-samsung-tv-65', available_quantity: 6, reserved_quantity: 0, sold_quantity: 4, version: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: 'inv-em-maa-logi', store_id: 'store-em-chennai', product_id: 'prod-logitech-mxmaster3s', available_quantity: 25, reserved_quantity: 0, sold_quantity: 50, version: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
];
